### ISSUE TITLE
Handle systems without root priviliges

### ISSUE THREAD

**Issue by claha** [claha/dotfiles#46]
I've encountered systems where I don't have root priviligies and thus can't install packages using pacman/apt. Talking with a llm chatbot gave me this solution which seems like a good approach

```yaml
  # Test sudo without password
  - name: Test sudo without password
    shell: sudo -n true
    register: sudo_test
    ignore_errors: true

  # Set a single fact based on either BECOME_PASS being present in the environment or the user can sudo without a password
  - set_fact:
      can_become: ("'BECOME_PASS' in env.stdout") or (sudo_test.rc == 0)
```
